[package]
name = "cami-benches"
version = "0.1.0"
edition = "2018"

[features]
alloc = ["cami/alloc"]
deref_pure = ["cami/deref_pure"]
std = ["alloc", "cami/std"]

[dependencies]

cami = { path = "../cami", version = "0.0.2", features = ["transmute", "debug"] }

[dev-dependencies]
# @TODO real_blackbox is on NIGHTLY only - is this depending on rustc channel?
# criterion = { version = "0.5.1", features=['real_blackbox'] }
criterion = { version = "0.5.1" }

fastrand = { version = "2.0.2"}

# For benches:
# ref-cast = "1.0"

[[bench]]
name = "vec_string"
harness = false
required-features = ["alloc"]

[[bench]]
name = "vec_u8"
harness = false
required-features = ["alloc"]

[[bench]]
name = "vec_u8slice"
harness = false
required-features = ["alloc"]

[[bench]]
name = "shared"
harness = false

[lints.rust]
warnings = "allow"
